/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.edroskos;

import com.typesafe.config.Config;
import com.typesafe.config.ConfigFactory;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void testSomeLibraryMethod() {
        Config conf = ConfigFactory.load();
        var defaultLanguage = conf.getString("net.edroskos.economy.i18n.defaultLanguage");
        var defaultCountry = conf.getString("net.edroskos.economy.i18n.defaultCountry");
        System.out.printf("i18n(%s.%s)\n", defaultLanguage, defaultCountry);

        assertTrue(true, "Yup, that works");
    }
}
